### ISSUE TITLE
Link in Repositories

### ISSUE THREAD

**Issue by LikwidShadow** [nds-swe/swdt#10]
The link in the repositories  mambax/abb-nds-hf-swe-exman1 does not work

**Comment by mambax** [comment]
Thanks for the pointer. I submitted a fix in https://github.com/nds-swe/swdt/pull/11

Yet, it will still not work for you, the packer is private:

![image](https://user-images.githubusercontent.com/5472171/114274459-c2090700-9a1e-11eb-8469-a94940e9c416.png)

You need to ask for access as asked here: https://nds-swe.github.io/swdt/docs/tasks/client-server#invite-to-packer

Since I know your handle now, could you check quickly in teams so I can verify who you are? 🕵🏼‍♂️

You have no information in your profile what so ever so I can not see if you are a student or not 😊

Upon verification that you are a student I will invite you to the packer straight away.

**Comment by mambax** [comment]
Resolved as per Teams discussion 👍🏽
