### ISSUE TITLE
Postman don`t work always

### ISSUE THREAD

**Issue by AZammu** [nds-swe/swdt#32]
Hi together

When I make a request in Postman, it doesn't work every time. Although is the request correct. 

Why I have this problem?

Thanks
Angela

**Comment by mambax** [comment]
Hi @AZammu 
We clarified this in the lesson, the problem was that you did not attach any body and that the Verb was set to `GET` instead of `POST`.

If you want to SEND some payload you might need `POST` (or sometimes `PUT`). Also you need to attach a payload as so called `body`.

You can see this here in detail:
https://github.com/nds-swe/swdt/blob/ac5b848f00b9436c3e8b92e334608f5ce22f5ae5/docs/tasks/assets/client-server-sample-solution.http#L39

Sunny weekend ☀️

**Comment by mambax** [comment]
PS: If you open an issue its always helpful to show what you tried and what the `error` is, so I can follow 👍🏼

Also, please remind that the `exman-packer` takes some time to start as defined here: https://nds-swe.github.io/swdt/docs/exman/suite#start-time
